version: "3.9"
networks:
  deploy-guide-dev:
    driver: bridge
services:
  postgres_db:
    container_name: postgres_db
    image: postgres:latest
    environment:
      POSTGRES_DB: Test5GProject
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
    ports:
      - "5432:5432"
    networks:
      - deploy-guide-dev
  webapi:
    container_name: deploy-guide
    build:
      context: .
      dockerfile: WebApi/Dockerfile
    ports:
      - "80:80"
    networks:
      - deploy-guide-dev
    depends_on:
      - postgres_db
  client:
    container_name: vue-front
    build:
      context: ./WebApi/app-vue
      dockerfile: Dockerfile
    ports:
      - "5001:8080"
    networks:
      - deploy-guide-dev
volumes:
  postgres-data: